# Week2 授業前課題3 行列積のスクラッチ

以下のような行列A、Bを考えます。

$$
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right]
$$

In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

### 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

$$ 
\left[
\begin{array}{ccc}
  (-1)\times0+2\times0+3\times2 & (-1)\times2+2\times2+3\times9 & (-1)\times1+2\times(-8)+3\times(-1) \\
  4\times0+(-5)\times0+6\times2 & 4\times2+(-5)\times2+6\times9 & 4\times1+(-5)\times(-8)+6\times(-1) \\
  7\times0+8\times0+(-9)\times2 & -7\times0+8\times2+(-9)\times9 & 7\times1+8\times(-8)+(-9)\times(-1)
\end{array}
\right]
=\left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]
$$

### 【問題2】NumPyの関数による計算
この行列積はNumPyの

- **`np.matmul()`**
- **`np.dot()`**
- **`@`**

を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

- **np.matmul()**

In [3]:
nd_array_matmul = np.matmul(a_ndarray, b_ndarray)
print(nd_array_matmul)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


- **np.dot()**

In [4]:
nd_array_dot = np.dot(a_ndarray, b_ndarray)
print(nd_array_dot)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


- **@**

In [5]:
nd_array_atto = a_ndarray @ b_ndarray
print(nd_array_atto)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### どの関数が一番計算が速いか

- **np.matmul()**

In [6]:
%%timeit
nd_array_matmul = np.matmul(a_ndarray, b_ndarray)

812 ns ± 11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


- **np.dot()**

In [7]:
%%timeit
nd_array_dot = np.dot(a_ndarray, b_ndarray)

935 ns ± 33.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


- **@**

In [8]:
%%timeit
nd_array_atto = a_ndarray @ b_ndarray

806 ns ± 37 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


**dot積が一番速い計算方法である。**

### 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

1. 行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
2. 行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる
3. 行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる
4. それらの値を全て足し合わせる

数式で表すと

$$
\sum^{2}_{k=0}a_{0,k}b_{k,0}
$$

です。

この計算を`np.matmul()`や`np.dot()`、または`@`演算子を使わずに行うコードを書いてください。

$$
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right]
$$

In [11]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ab1_ndarray = sum(a_ndarray[0, :] * b_ndarray[:, 0])
print(ab1_ndarray)

6


### 【問題4】行列積を行う関数の作成

問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。

$$
c_{i,j} = \sum^{2}_{k=0}a_{i,k}b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。

$$
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right]
$$

- おさらい

In [32]:
z = np.array([[1,2,3],[4,5,6]])
print(z)
print(z.shape)#２行３列
print(z.shape[0])#行数
print(z.shape[1])#列数
print()

[[1 2 3]
 [4 5 6]]
(2, 3)
2
3


In [41]:
def gyouretsuseki2(a , b):
    
    c = np.empty((a.shape[0], b.shape[1]))#初期化した配列に、aのインデックス0と、bのインデックス[1]を代入する

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i, j] = (a[i]*b[:, j]).sum()
    return c

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(gyouretsuseki2(a_ndarray , b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


次に以下のような例を考えます。    

$$ D = \left[
    \begin{array}{ccc}
      -1 & 2 & 3 \\
      4 & -5 & 6
    \end{array}
  \right],
  E = \left[
    \begin{array}{ccc}
       -9 & 8 & 7 \\
      6 & -5 & 4
    \end{array}
  \right] $$

```py
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
```

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

### 【問題5】計算が定義されない入力を判定する

問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることを`print()`を使い表示するコードを書き加えてください。

In [55]:
def gyouretuseki3(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    if a.shape[0] == b.shape[1]:
        for i in range(a.shape[0]):
            for j in range(b.shape[1]):
                c[i, j] = (a[i]*b[:, j]).sum()
        return c
    else:
        print("{}! = {}".format(a.shape[0], b.shape[1]))

d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print(gyouretuseki3(d, e))

2! = 3
None


- assertを用いる場合

In [62]:
def matrix_product_q5_2(a, b):
    c = np.empty((a.shape[0], b.shape[1]))

    assert a.shape[0] == b.shape[1], "a.shape[0] != b.shape[1] : {} != {}".format(a.shape[0], b.shape[1])
    for i in range(a.shape[0]):
            for j in range(b.shape[1]):
                c[i, j] = (a[i]*b[:, j]).sum()
    return c
        
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果\n{}".format(matrix_product_q5_2(d, e)))

AssertionError: a.shape[0] != b.shape[1] : 2 != 3

### 【問題6】転置
**ポイント：行と列の数を合わせれば計算可能！**


片方の行列を転置することで、行列積が計算できるようになります。

- dを転置した場合

In [57]:
#計算結果１：dを転置した場合
#計算結果２：eを転置した場合
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])

print("計算結果1：\n{}".format(np.dot(d.T, e)))


計算結果1：
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]


- eを転置した場合

In [58]:
print("計算結果2：\n{}".format(np.dot(d, e.T)))

計算結果2：
[[ 46  -4]
 [-34  73]]
